name: Build Android Kernel for S922X

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-kernel:
    runs-on: ubuntu-latest

    env:
      ARCH: arm64
      CROSS_COMPILE: aarch64-linux-android-
      KERNEL_DEFCONFIG: odroidn2_android_defconfig
      KERNEL_SOURCE: android_kernel_voodik_odroidg12
      KERNEL_BRANCH: lineage-20.0_odroidg12_t_64_r44

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y bc bison flex libssl-dev make gcc \
          libncurses5-dev libelf-dev git wget curl build-essential

    - name: Download Android NDK
      run: |
        wget https://dl.google.com/android/repository/android-ndk-r21e-linux-x86_64.zip
        unzip android-ndk-r21e-linux-x86_64.zip
        echo "NDK path: $PWD/android-ndk-r21e"

    - name: Set environment variables
      run: |
        echo "PATH=$PWD/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH" >> $GITHUB_ENV
        echo "CROSS_COMPILE=aarch64-linux-android-" >> $GITHUB_ENV
        echo "ARCH=arm64" >> $GITHUB_ENV
        
    - name: Clone kernel source
      run: |
        git clone https://github.com/voodik/${{ env.KERNEL_SOURCE }} -b ${{ env.KERNEL_BRANCH }} kernel

    - name: Build kernel
      working-directory: kernel
      run: |
        make ARCH=$ARCH $KERNEL_DEFCONFIG
        make ARCH=$ARCH -j$(nproc)

    - name: Upload kernel artifacts
      uses: actions/upload-artifact@v4
      with:
        name: kernel-build
        path: |
          arch/arm64/boot/Image
          arch/arm64/boot/dts/amlogic/*.dtb
